In [1]:
import torch
import csv
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import classification_report
import ast

In [2]:
X=[]
y=[]
Xpos=[]
ypos=[]
namespos=[]
names=[]


In [3]:
from google.colab import drive
drive.mount('/content/drive')
with open('/content/drive/My Drive/MicroMinerDataMustafa/MicroMiner/posclassEmbadding2.csv', newline='') as classEmbaddings:
    reader = csv.reader(classEmbaddings, delimiter=';')
    for row in reader:
        X.append(ast.literal_eval(row[2]))
        y.append(row[1])
        names.append(row[0])

Mounted at /content/drive


In [4]:
X_train, X_test, y_trainnames, y_testnames = train_test_split(X, names, test_size=0.3, train_size=0.7, random_state = 42)
y_train=[]
y_test=[]
for yt in y_trainnames:
    y_train.append(y[names.index(yt)])
for yt in y_testnames:
    y_test.append(y[names.index(yt)])
utilityyes=False
for yitem in y_train:
    if(yitem=="utility"):
        utilityyes=True
if not utilityyes:
    for i,yitem in enumerate(y):
        if(yitem=="utility"):
            y_train.append("utility")
            X_train.append(X[i])
            break


In [5]:
from sklearn.tree import DecisionTreeClassifier
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)
cm = confusion_matrix(y_test, dtree_predictions)

from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, dtree_predictions)

In [6]:
print(score)
print(cm)
#({'entity': 793, 'utility': 180, 'application': 168})
from sklearn.metrics import precision_recall_fscore_support
hh=precision_recall_fscore_support(y_test, dtree_predictions, average='macro')
print(classification_report(y_test, dtree_predictions, target_names=['Class 1', 'Class 2', 'Class 3']))


0.8235294117647058
[[8 1 0]
 [1 6 0]
 [1 0 0]]
              precision    recall  f1-score   support

     Class 1       0.80      0.89      0.84         9
     Class 2       0.86      0.86      0.86         7
     Class 3       0.00      0.00      0.00         1

    accuracy                           0.82        17
   macro avg       0.55      0.58      0.57        17
weighted avg       0.78      0.82      0.80        17



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif

In [7]:
from sklearn.svm import SVC
svm_model_linear = SVC(kernel = 'linear', C = 2).fit(X_train, y_train)
svm_predictions = svm_model_linear.predict(X_test)
# model accuracy for X_test
accuracysvm = svm_model_linear.score(X_test, y_test)

# creating a confusion matrix
cmsvm = confusion_matrix(y_test, svm_predictions)
print(accuracysvm)
print(cmsvm)
print(classification_report(y_test, svm_predictions, target_names=['Class 1', 'Class 2', 'Class 3']))



0.9411764705882353
[[9 0 0]
 [0 7 0]
 [1 0 0]]
              precision    recall  f1-score   support

     Class 1       0.90      1.00      0.95         9
     Class 2       1.00      1.00      1.00         7
     Class 3       0.00      0.00      0.00         1

    accuracy                           0.94        17
   macro avg       0.63      0.67      0.65        17
weighted avg       0.89      0.94      0.91        17



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
Y_all=np.concatenate((y_train,svm_predictions))
labelTrue=np.concatenate((y_train,y_test))
Names_all=np.concatenate((y_trainnames,y_testnames))
entities=[]
applications=[]
utilities=[]
for idx, prediction in zip(enumerate(Y_all),Y_all):
    if(prediction == "application"):
        applications.append(Names_all[idx[0]])
    elif(prediction == "entity"):
        entities.append(Names_all[idx[0]])
    elif(prediction == "utility"):
        utilities.append(Names_all[idx[0]])
file1 = open("entity.txt","w+")
for e in entities:
    file1.write(e)
    file1.write("\n")
file1.close()
file1 = open("application.txt","w+")
for e in applications:
    file1.write(e)
    file1.write("\n")
file1.close()
file1 = open("utility.txt","w+")
for e in utilities:
    file1.write(e)
    file1.write("\n")
file1.close()

In [9]:
# training a KNN classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5).fit(X_train, y_train)

# accuracy on X_test
accuracyknn = knn.score(X_test, y_test)
print (accuracyknn)

# creating a confusion matrix
knn_predictions = knn.predict(X_test)
cmknn = confusion_matrix(y_test, knn_predictions)
print(cmknn)
print(classification_report(y_test, knn_predictions, target_names=['Class 1', 'Class 2', 'Class 3']))


0.9411764705882353
[[9 0 0]
 [0 7 0]
 [1 0 0]]
              precision    recall  f1-score   support

     Class 1       0.90      1.00      0.95         9
     Class 2       1.00      1.00      1.00         7
     Class 3       0.00      0.00      0.00         1

    accuracy                           0.94        17
   macro avg       0.63      0.67      0.65        17
weighted avg       0.89      0.94      0.91        17



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
clf_predictions = clf.predict(X_test)
cmclf = confusion_matrix(y_test, clf_predictions)
# accuracy on X_test
accuracycmclf = clf.score(X_test, y_test)
print (accuracycmclf)
print(cmclf)
print(classification_report(y_test, clf_predictions, target_names=['Class 1', 'Class 2', 'Class 3']))

0.9411764705882353
[[9 0 0]
 [0 7 0]
 [1 0 0]]
              precision    recall  f1-score   support

     Class 1       0.90      1.00      0.95         9
     Class 2       1.00      1.00      1.00         7
     Class 3       0.00      0.00      0.00         1

    accuracy                           0.94        17
   macro avg       0.63      0.67      0.65        17
weighted avg       0.89      0.94      0.91        17



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels wit

In [13]:
# training a Naive Bayes classifier
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, y_train)
gnb_predictions = gnb.predict(X_test)

# accuracy on X_test
gnb_accuracy = gnb.score(X_test, y_test)

# creating a confusion matrix
gnb_cm = confusion_matrix(y_test, gnb_predictions)
print(gnb_accuracy)
print(gnb_cm)

print(classification_report(y_test, gnb_predictions, target_names=['Class 1', 'Class 2', 'Class 3']))

0.9411764705882353
[[9 0 0]
 [0 7 0]
 [1 0 0]]
              precision    recall  f1-score   support

     Class 1       0.90      1.00      0.95         9
     Class 2       1.00      1.00      1.00         7
     Class 3       0.00      0.00      0.00         1

    accuracy                           0.94        17
   macro avg       0.63      0.67      0.65        17
weighted avg       0.89      0.94      0.91        17



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Random Forest sınıflandırıcıyı eğitme
rf_classifier = RandomForestClassifier().fit(X_train, y_train)

# X_test üzerinde tahmin yapma
rf_predictions = rf_classifier.predict(X_test)

# X_test üzerinde doğruluk hesaplama
rf_accuracy = accuracy_score(y_test, rf_predictions)

# Karışıklık matrisi oluşturma
rf_cm = confusion_matrix(y_test, rf_predictions)
print("Accuracy:", rf_accuracy)
print("Confusion Matrix:\n", rf_cm)

# Sınıflandırma raporu oluşturma
print(classification_report(y_test, rf_predictions, target_names=['Class 1', 'Class 2', 'Class 3']))


Accuracy: 0.9411764705882353
Confusion Matrix:
 [[9 0 0]
 [0 7 0]
 [1 0 0]]
              precision    recall  f1-score   support

     Class 1       0.90      1.00      0.95         9
     Class 2       1.00      1.00      1.00         7
     Class 3       0.00      0.00      0.00         1

    accuracy                           0.94        17
   macro avg       0.63      0.67      0.65        17
weighted avg       0.89      0.94      0.91        17



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
